-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 20:32:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `idAirport` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(85) NOT NULL,
  `Country` VARCHAR(56) NOT NULL,
  `IATA code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idAirport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `Model Name` VARCHAR(12) NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `Seat number` INT NOT NULL,
  `Weight` FLOAT NOT NULL,
  PRIMARY KEY (`Model Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aircraft` (
  `idAircraft` INT NOT NULL,
  `Model_Model Name` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idAircraft`, `Model_Model Name`),
  INDEX `fk_Aircraft_Model1_idx` (`Model_Model Name` ASC) VISIBLE,
  CONSTRAINT `fk_Aircraft_Model1`
    FOREIGN KEY (`Model_Model Name`)
    REFERENCES `mydb`.`Model` (`Model Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airline` (
  `Name` VARCHAR(56) NOT NULL,
  `Origin Country` VARCHAR(45) NOT NULL,
  `International Company id` INT NOT NULL,
  `Active` TINYINT NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `idFlight` INT NOT NULL,
  `Departure` DATETIME NOT NULL,
  `Arrival` DATETIME NOT NULL,
  `Airline_Name` VARCHAR(56) NOT NULL,
  `Departing Airport_idAirport` INT NOT NULL,
  `Arriving Airport_idAirport` INT NOT NULL,
  `Aircraft_idAircraft` INT NOT NULL,
  `Aircraft_Model_Model Name` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idFlight`),
  INDEX `fk_Flight_Airline1_idx` (`Airline_Name` ASC) VISIBLE,
  INDEX `fk_Flight_Airport1_idx` (`Departing Airport_idAirport` ASC) VISIBLE,
  INDEX `fk_Flight_Airport2_idx` (`Arriving Airport_idAirport` ASC) VISIBLE,
  INDEX `fk_Flight_Aircraft1_idx` (`Aircraft_idAircraft` ASC, `Aircraft_Model_Model Name` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_Airline1`
    FOREIGN KEY (`Airline_Name`)
    REFERENCES `mydb`.`Airline` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airport1`
    FOREIGN KEY (`Departing Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airport2`
    FOREIGN KEY (`Arriving Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Aircraft1`
    FOREIGN KEY (`Aircraft_idAircraft` , `Aircraft_Model_Model Name`)
    REFERENCES `mydb`.`Aircraft` (`idAircraft` , `Model_Model Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `ID` VARCHAR(8) NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Surname` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(10) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccine Certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccine Certificate` (
  `idVaccine Certificate` INT NOT NULL,
  `Doses` INT NOT NULL,
  `Last Dose Date` DATE NOT NULL,
  PRIMARY KEY (`idVaccine Certificate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `Passport` INT NOT NULL,
  `Person_ID` VARCHAR(8) NOT NULL,
  `Vaccine Certificate_idVaccine Certificate` INT NOT NULL,
  PRIMARY KEY (`Passport`, `Person_ID`),
  INDEX `fk_Passenger_Person1_idx` (`Person_ID` ASC) VISIBLE,
  INDEX `fk_Passenger_Vaccine Certificate1_idx` (`Vaccine Certificate_idVaccine Certificate` ASC) VISIBLE,
  CONSTRAINT `fk_Passenger_Person1`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `mydb`.`Person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passenger_Vaccine Certificate1`
    FOREIGN KEY (`Vaccine Certificate_idVaccine Certificate`)
    REFERENCES `mydb`.`Vaccine Certificate` (`idVaccine Certificate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Union`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Union` (
  `Name` VARCHAR(45) NOT NULL,
  `Year founded` YEAR NOT NULL,
  `Members' ids` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician` (
  `Technician ID` INT NOT NULL,
  `Salary` FLOAT NOT NULL,
  `Person_ID` VARCHAR(8) NOT NULL,
  `Union_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Technician ID`, `Person_ID`),
  INDEX `fk_Technician_Person1_idx` (`Person_ID` ASC) VISIBLE,
  INDEX `fk_Technician_Union1_idx` (`Union_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Technician_Person1`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `mydb`.`Person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_Union1`
    FOREIGN KEY (`Union_Name`)
    REFERENCES `mydb`.`Union` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical Evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical Evaluation` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Air-traffic Controller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Air-traffic Controller` (
  `Air-traffic Controller ID` INT NOT NULL,
  `Latest check-up` DATE NOT NULL,
  `Person_ID` VARCHAR(8) NOT NULL,
  `Medical Evaluation_Name` VARCHAR(45) NOT NULL,
  `Airport_idAirport` INT NOT NULL,
  `Union_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Air-traffic Controller ID`, `Person_ID`, `Airport_idAirport`),
  INDEX `fk_Air-traffic Controller_Person1_idx` (`Person_ID` ASC) VISIBLE,
  INDEX `fk_Air-traffic Controller_Medical Evaluation1_idx` (`Medical Evaluation_Name` ASC) VISIBLE,
  INDEX `fk_Air-traffic Controller_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  INDEX `fk_Air-traffic Controller_Union1_idx` (`Union_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Air-traffic Controller_Person1`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `mydb`.`Person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Air-traffic Controller_Medical Evaluation1`
    FOREIGN KEY (`Medical Evaluation_Name`)
    REFERENCES `mydb`.`Medical Evaluation` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Air-traffic Controller_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Air-traffic Controller_Union1`
    FOREIGN KEY (`Union_Name`)
    REFERENCES `mydb`.`Union` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Civil Aviation Authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Civil Aviation Authority` (
  `Country` VARCHAR(56) NOT NULL,
  PRIMARY KEY (`Country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inspection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inspection` (
  `YPA code` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Maximum Score` INT NOT NULL,
  `Civil Aviation Authority_Country` VARCHAR(56) NOT NULL,
  PRIMARY KEY (`YPA code`),
  INDEX `fk_Inspection_Civil Aviation Authority1_idx` (`Civil Aviation Authority_Country` ASC) VISIBLE,
  CONSTRAINT `fk_Inspection_Civil Aviation Authority1`
    FOREIGN KEY (`Civil Aviation Authority_Country`)
    REFERENCES `mydb`.`Civil Aviation Authority` (`Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inspect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inspect` (
  `Date` DATE NOT NULL,
  `Hours to completion` INT NOT NULL,
  `Score` INT NOT NULL,
  `Technician_Technician ID` INT NOT NULL,
  `Technician_Person_ID` VARCHAR(8) NOT NULL,
  `Inspection_YPA code` INT NOT NULL,
  `Aircraft_idAircraft` INT NOT NULL,
  `Aircraft_Model_Model Name` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Technician_Technician ID`, `Technician_Person_ID`, `Inspection_YPA code`, `Aircraft_idAircraft`, `Aircraft_Model_Model Name`),
  INDEX `fk_Inspect_Inspection1_idx` (`Inspection_YPA code` ASC) VISIBLE,
  INDEX `fk_Inspect_Aircraft1_idx` (`Aircraft_idAircraft` ASC, `Aircraft_Model_Model Name` ASC) VISIBLE,
  CONSTRAINT `fk_Inspect_Technician1`
    FOREIGN KEY (`Technician_Technician ID` , `Technician_Person_ID`)
    REFERENCES `mydb`.`Technician` (`Technician ID` , `Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inspect_Inspection1`
    FOREIGN KEY (`Inspection_YPA code`)
    REFERENCES `mydb`.`Inspection` (`YPA code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inspect_Aircraft1`
    FOREIGN KEY (`Aircraft_idAircraft` , `Aircraft_Model_Model Name`)
    REFERENCES `mydb`.`Aircraft` (`idAircraft` , `Model_Model Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Search` (
  `Type` SET("One-Way", "Return") NOT NULL,
  `Date` DATE NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Details` TEXT NOT NULL,
  `Search_Type` SET("One-Way", "Return") NULL,
  `Search_Date` DATE NULL,
  PRIMARY KEY (`Type`, `Date`),
  INDEX `fk_Search_Search1_idx` (`Search_Type` ASC, `Search_Date` ASC) VISIBLE,
  CONSTRAINT `fk_Search_Search1`
    FOREIGN KEY (`Search_Type` , `Search_Date`)
    REFERENCES `mydb`.`Search` (`Type` , `Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `MenuType` SET("First Class", "Business Class", "Premium Economy", "Economy Class") NOT NULL,
  `Details` TEXT NOT NULL,
  PRIMARY KEY (`MenuType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seat` (
  `Seat Number` VARCHAR(3) NOT NULL,
  `Type` SET("First Class", "Business Class", "Premium Economy", "Economy Class") NOT NULL,
  `Menu_MenuType` SET("First Class", "Business Class", "Premium Economy", "Economy Class") NOT NULL,
  PRIMARY KEY (`Seat Number`),
  INDEX `fk_Seat_Menu1_idx` (`Menu_MenuType` ASC) VISIBLE,
  CONSTRAINT `fk_Seat_Menu1`
    FOREIGN KEY (`Menu_MenuType`)
    REFERENCES `mydb`.`Menu` (`MenuType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Booking System`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Booking System` (
  `booking id` INT NOT NULL,
  `date` DATE NOT NULL,
  `comments` TEXT NULL,
  `Seat_Seat Number` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`booking id`),
  INDEX `fk_Booking System_Seat1_idx` (`Seat_Seat Number` ASC) VISIBLE,
  CONSTRAINT `fk_Booking System_Seat1`
    FOREIGN KEY (`Seat_Seat Number`)
    REFERENCES `mydb`.`Seat` (`Seat Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight Manifest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight Manifest` (
  `Manifest ID` INT NOT NULL,
  `Flight_idFlight` INT NOT NULL,
  PRIMARY KEY (`Manifest ID`),
  INDEX `fk_Manifest_Flight1_idx` (`Flight_idFlight` ASC) VISIBLE,
  CONSTRAINT `fk_Manifest_Flight1`
    FOREIGN KEY (`Flight_idFlight`)
    REFERENCES `mydb`.`Flight` (`idFlight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Qr code` INT NOT NULL,
  `idTicket` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Passenger_Passport` INT NOT NULL,
  `Passenger_Person_ID` VARCHAR(8) NOT NULL,
  `Booking System_booking id` INT NOT NULL,
  `Manifest_Manifest ID` INT NOT NULL,
  PRIMARY KEY (`Qr code`),
  INDEX `fk_Ticket_Passenger1_idx` (`Passenger_Passport` ASC, `Passenger_Person_ID` ASC) VISIBLE,
  INDEX `fk_Ticket_Booking System1_idx` (`Booking System_booking id` ASC) VISIBLE,
  INDEX `fk_Ticket_Manifest1_idx` (`Manifest_Manifest ID` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Passenger1`
    FOREIGN KEY (`Passenger_Passport` , `Passenger_Person_ID`)
    REFERENCES `mydb`.`Passenger` (`Passport` , `Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Booking System1`
    FOREIGN KEY (`Booking System_booking id`)
    REFERENCES `mydb`.`Booking System` (`booking id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Manifest1`
    FOREIGN KEY (`Manifest_Manifest ID`)
    REFERENCES `mydb`.`Flight Manifest` (`Manifest ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Through Webpage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Through Webpage` (
  `Passenger_Passport` INT NOT NULL,
  `Passenger_Person_ID` VARCHAR(8) NOT NULL,
  `Search_Type` SET("One-Way", "Return") NOT NULL,
  `Search_Date` DATE NOT NULL,
  `Booking System_booking id` INT NOT NULL,
  PRIMARY KEY (`Passenger_Passport`, `Passenger_Person_ID`, `Search_Type`, `Search_Date`, `Booking System_booking id`),
  INDEX `fk_Through Webpage_Search1_idx` (`Search_Type` ASC, `Search_Date` ASC) VISIBLE,
  INDEX `fk_Through Webpage_Booking System1_idx` (`Booking System_booking id` ASC) VISIBLE,
  CONSTRAINT `fk_Through Webpage_Passenger1`
    FOREIGN KEY (`Passenger_Passport` , `Passenger_Person_ID`)
    REFERENCES `mydb`.`Passenger` (`Passport` , `Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Through Webpage_Search1`
    FOREIGN KEY (`Search_Type` , `Search_Date`)
    REFERENCES `mydb`.`Search` (`Type` , `Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Through Webpage_Booking System1`
    FOREIGN KEY (`Booking System_booking id`)
    REFERENCES `mydb`.`Booking System` (`booking id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport_has_Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport_has_Airline` (
  `Airport_idAirport` INT NOT NULL,
  `Airline_Name` VARCHAR(56) NOT NULL,
  PRIMARY KEY (`Airport_idAirport`, `Airline_Name`),
  INDEX `fk_Airport_has_Airline_Airline1_idx` (`Airline_Name` ASC) VISIBLE,
  INDEX `fk_Airport_has_Airline_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_has_Airline_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_has_Airline_Airline1`
    FOREIGN KEY (`Airline_Name`)
    REFERENCES `mydb`.`Airline` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight_has_Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight_has_Menu` (
  `Flight_idFlight` INT NOT NULL,
  `Menu_MenuType` SET("First Class", "Business Class", "Premium Economy", "Economy Class") NOT NULL,
  PRIMARY KEY (`Flight_idFlight`, `Menu_MenuType`),
  INDEX `fk_Flight_has_Menu_Menu1_idx` (`Menu_MenuType` ASC) VISIBLE,
  INDEX `fk_Flight_has_Menu_Flight1_idx` (`Flight_idFlight` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_has_Menu_Flight1`
    FOREIGN KEY (`Flight_idFlight`)
    REFERENCES `mydb`.`Flight` (`idFlight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_has_Menu_Menu1`
    FOREIGN KEY (`Menu_MenuType`)
    REFERENCES `mydb`.`Menu` (`MenuType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Search_for_Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Search_for_Flight` (
  `Search_Type` SET("One-Way", "Return") NOT NULL,
  `Search_Date` DATE NOT NULL,
  `Flight_idFlight` INT NOT NULL,
  PRIMARY KEY (`Search_Type`, `Search_Date`, `Flight_idFlight`),
  INDEX `fk_Search_has_Flight_Flight1_idx` (`Flight_idFlight` ASC) VISIBLE,
  INDEX `fk_Search_has_Flight_Search1_idx` (`Search_Type` ASC, `Search_Date` ASC) VISIBLE,
  CONSTRAINT `fk_Search_has_Flight_Search1`
    FOREIGN KEY (`Search_Type` , `Search_Date`)
    REFERENCES `mydb`.`Search` (`Type` , `Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Search_has_Flight_Flight1`
    FOREIGN KEY (`Flight_idFlight`)
    REFERENCES `mydb`.`Flight` (`idFlight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specialization` (
  `Technician_Technician ID` INT NOT NULL,
  `Technician_Person_ID` VARCHAR(8) NOT NULL,
  `Model_Model Name` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Technician_Technician ID`, `Technician_Person_ID`, `Model_Model Name`),
  INDEX `fk_Technician_has_Model_Model1_idx` (`Model_Model Name` ASC) VISIBLE,
  INDEX `fk_Technician_has_Model_Technician1_idx` (`Technician_Technician ID` ASC, `Technician_Person_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Technician_has_Model_Technician1`
    FOREIGN KEY (`Technician_Technician ID` , `Technician_Person_ID`)
    REFERENCES `mydb`.`Technician` (`Technician ID` , `Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_has_Model_Model1`
    FOREIGN KEY (`Model_Model Name`)
    REFERENCES `mydb`.`Model` (`Model Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport_has_Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport_has_Aircraft` (
  `Airport_idAirport` INT NOT NULL,
  `Aircraft_idAircraft` INT NOT NULL,
  `Aircraft_Model_Model Name` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Airport_idAirport`, `Aircraft_idAircraft`, `Aircraft_Model_Model Name`),
  INDEX `fk_Airport_has_Aircraft_Aircraft1_idx` (`Aircraft_idAircraft` ASC, `Aircraft_Model_Model Name` ASC) VISIBLE,
  INDEX `fk_Airport_has_Aircraft_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_has_Aircraft_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_has_Aircraft_Aircraft1`
    FOREIGN KEY (`Aircraft_idAircraft` , `Aircraft_Model_Model Name`)
    REFERENCES `mydb`.`Aircraft` (`idAircraft` , `Model_Model Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport_has_Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport_has_Technician` (
  `Airport_idAirport` INT NOT NULL,
  `Technician_Technician ID` INT NOT NULL,
  `Technician_Person_ID` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`Airport_idAirport`, `Technician_Technician ID`, `Technician_Person_ID`),
  INDEX `fk_Airport_has_Technician_Technician1_idx` (`Technician_Technician ID` ASC, `Technician_Person_ID` ASC) VISIBLE,
  INDEX `fk_Airport_has_Technician_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_has_Technician_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_has_Technician_Technician1`
    FOREIGN KEY (`Technician_Technician ID` , `Technician_Person_ID`)
    REFERENCES `mydb`.`Technician` (`Technician ID` , `Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
